# Generated by Django 5.2.10 on 2026-01-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
